---
- hosts: all
  become: true
  tasks:
    - name: Enable PoE+ Hat for Raspberry Pi
      template:
        src: config.txt.j2
        dest: /boot/firmware/config.txt
        owner: root
        group: root
        mode: 0755
    - name: Configure Boot Options
      template:
        src: cmdline.txt.j2
        dest: /boot/firmware/cmdline.txt
        owner: root
        group: root
        mode: 0755
    - name: Configure Hosts
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
    - name: Configure Hostname
      template:
        src: hostname.j2
        dest: /etc/hostname
        owner: root
        group: root
        mode: 0644
    - name: Reboot after Enabling PoE+ Hat
      reboot:
    - name: Update Packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: dist
    - name: Install Vim
      apt:
        name: vim
        state: latest
    - name: Reboot after Initial Setup
      reboot:
